[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "cloud-threat-detector"
version = "0.1.0"
description = "Cloud security scanner for detecting threats"
requires-python = ">=3.8"

[tool.setuptools]
packages = ["scanner", "backend"]